import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Providers from "@/lib/Providers/Providers";
import ReduxProvider from "@/redux/provider/Provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <Providers>
        <html lang="en">
          <body className={inter.className}>
         <ReduxProvider>   <AntdRegistry>{children}</AntdRegistry></ReduxProvider>
         <Toaster />
          </body>

        </html>
      </Providers>
    
  );
}
